language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    # PHP 7 testing is disabled for now because it is unstable
    - php: 7
    # We cannot use hhvm-nightly since that does not work in Travis CI's old
    # Ubuntu 12.04.
    - php: hhvm
  # Don't wait for the allowed failures to build.
  fast_finish: true

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit
