# For PHP 5.5 and lower testing we need to stick to Ubuntu 14.04.
dist: trusty
language: php
sudo: false

# Cache composer vendor directories to speed up the composer install step.
cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - composer.lock

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

before_install:
  # Speed up build time by disabling Xdebug when its not needed.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

before_script:
  # Run install in case the cached vendor directory is not present.
  - composer install
  # Always run tests with up to date dependencies.
  - composer update

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs -p
  - ./vendor/bin/phpcs -p --standard=coder_sniffer/Drupal/Test/phpcs-ruleset.xml coder_sniffer/Drupal/Test/good/ --ignore=coder_sniffer/Drupal/Test/good/GoodUnitTest.php
