language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
  - composer install
  - cp -r ./vendor/drupal/coder/coder_sniffer/Drupal ./vendor/squizlabs/php_codesniffer/CodeSniffer/Standards
script: phpcs --standard=./DrupalPractice Test/good.php
